### ISSUE TITLE
[bug]: RangeError: Maximum call stack size exceeded when using useTrail

### ISSUE THREAD

**Issue by thexpand** [pmndrs/react-spring#1810]
### Which react-spring target are you using?

`@react-spring/web`

### What version of react-spring are you using?

9.4.2

### What's Wrong?

This happens when I try to call the `useTrail`'s API method `start`. It started happening after version 9.4.0. I didn't have this problem with version 9.3.2. I looked into the changes between the 2 versions and I noticed this:
https://github.com/pmndrs/react-spring/commit/655ded7cf6270bc0222e196eb3601baabb45c6e8#diff-e2e32d84c9f46068f934f0f43993ab7f1fe012f24dafe23301fb447ebbe4f0ddR76-R96

It may be related somehow, but I'm not sure how.
Here's the trace:
```
react-spring-core.esm.js?8ada:973 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at SpringValue.eventObserved (react-spring-core.esm.js?8ada:973:1)
    at callFluidObserver (react-spring-shared.esm.js?569f:522:1)
    at eval (react-spring-shared.esm.js?569f:533:1)
    at Set.forEach (<anonymous>)
    at callFluidObservers (react-spring-shared.esm.js?569f:532:1)
    at SpringValue._onPriorityChange (react-spring-core.esm.js?8ada:665:23)
    at SpringValue.set priority [as priority] (react-spring-core.esm.js?8ada:617:1)
    at SpringValue.eventObserved (react-spring-core.esm.js?8ada:977:1)
    at callFluidObserver (react-spring-shared.esm.js?569f:522:1)
    at eval (react-spring-shared.esm.js?569f:533:1)
    at Set.forEach (<anonymous>)
    at callFluidObservers (react-spring-shared.esm.js?569f:532:1)
    at SpringValue._onPriorityChange (react-spring-core.esm.js?8ada:665:23)
    at SpringValue.set priority [as priority] (react-spring-core.esm.js?8ada:617:1)
    at SpringValue.eventObserved (react-spring-core.esm.js?8ada:977:1)
    at callFluidObserver (react-spring-shared.esm.js?569f:522:1)
    at eval (react-spring-shared.esm.js?569f:533:1)
    at Set.forEach (<anonymous>)
    at callFluidObservers (react-spring-shared.esm.js?569f:532:1)
    at SpringValue._onPriorityChange (react-spring-core.esm.js?8ada:665:23)
    at SpringValue.set priority [as priority] (react-spring-core.esm.js?8ada:617:1)
    at SpringValue.eventObserved (react-spring-core.esm.js?8ada:977:1)
    at callFluidObserver (react-spring-shared.esm.js?569f:522:1)
    at eval (react-spring-shared.esm.js?569f:533:1)
    at Set.forEach (<anonymous>)
    at callFluidObservers (react-spring-shared.esm.js?569f:532:1)
    at SpringValue._onPriorityChange (react-spring-core.esm.js?8ada:665:23)
    at SpringValue.set priority [as priority] (react-spring-core.esm.js?8ada:617:1)
    at SpringValue.eventObserved (react-spring-core.esm.js?8ada:977:1)
    at callFluidObserver (react-spring-shared.esm.js?569f:522:1)
    at eval (react-spring-shared.esm.js?569f:533:1)
    at Set.forEach (<anonymous>)
    at callFluidObservers (react-spring-shared.esm.js?569f:532:1)
    at SpringValue._onPriorityChange (react-spring-core.esm.js?8ada:665:23)
    at SpringValue.set priority [as priority] (react-spring-core.esm.js?8ada:617:1)
    at SpringValue.eventObserved (react-spring-core.esm.js?8ada:977:1)
    at callFluidObserver (react-spring-shared.esm.js?569f:522:1)
    at eval (react-spring-shared.esm.js?569f:533:1)
    at Set.forEach (<anonymous>)
    at callFluidObservers (react-spring-shared.esm.js?569f:532:1)
    at SpringValue._onPriorityChange (react-spring-core.esm.js?8ada:665:23)
    at SpringValue.set priority [as priority] (react-spring-core.esm.js?8ada:617:1)
    at SpringValue.eventObserved (react-spring-core.esm.js?8ada:977:1)
    at callFluidObserver (react-spring-shared.esm.js?569f:522:1)
    at eval (react-spring-shared.esm.js?569f:533:1)
    at Set.forEach (<anonymous>)
    at callFluidObservers (react-spring-shared.esm.js?569f:532:1)
    at SpringValue._onPriorityChange (react-spring-core.esm.js?8ada:665:23)
    at SpringValue.set priority [as priority] (react-spring-core.esm.js?8ada:617:1)
    at SpringValue.eventObserved (react-spring-core.esm.js?8ada:977:1)
```

And when expanded, it looks like this:
FYI: `MobileNavigation.js?d1ac:175` is where I call the `start` function of the `useTrail`'s API.
```
Promise.then (async) |   |  
-- | -- | --
  | flushUpdateQueue | @ | react-spring-core.esm.js?8ada:1639
  | flush | @ | react-spring-core.esm.js?8ada:1958
  | start | @ | react-spring-core.esm.js?8ada:1534
  | eval | @ | react-spring-core.esm.js?8ada:2084
  | each | @ | react-spring-shared.esm.js?569f:33
  | ref.start | @ | react-spring-core.esm.js?8ada:2079
  | eval | @ | MobileNavigation.js?d1ac:175
  | setTimeout (async) |   |  
  | eval | @ | MobileNavigation.js?d1ac:174
  | eval | @ | MobileNavigation.js?d1ac:219
  | invokePassiveEffectCreate | @ | react-dom.development.js?ac89:23487
  | callCallback | @ | react-dom.development.js?ac89:3945
  | invokeGuardedCallbackDev | @ | react-dom.development.js?ac89:3994
  | invokeGuardedCallback | @ | react-dom.development.js?ac89:4056
  | flushPassiveEffectsImpl | @ | react-dom.development.js?ac89:23574
  | unstable_runWithPriority | @ | scheduler.development.js?bcd2:468
  | runWithPriority$1 | @ | react-dom.development.js?ac89:11276
  | flushPassiveEffects | @ | react-dom.development.js?ac89:23447
  | performSyncWorkOnRoot | @ | react-dom.development.js?ac89:22269
  | eval | @ | react-dom.development.js?ac89:11327
  | unstable_runWithPriority | @ | scheduler.development.js?bcd2:468
  | runWithPriority$1 | @ | react-dom.development.js?ac89:11276
  | flushSyncCallbackQueueImpl | @ | react-dom.development.js?ac89:11322
  | flushSyncCallbackQueue | @ | react-dom.development.js?ac89:11309
  | batchedUpdates$1 | @ | react-dom.development.js?ac89:22387
  | loop | @ | react-spring-rafz.esm.js?08aa:133
  | requestAnimationFrame (async) |   |  
  | loop | @ | react-spring-rafz.esm.js?08aa:132
  | requestAnimationFrame (async) |   |  
  | loop | @ | react-spring-rafz.esm.js?08aa:132
  | requestAnimationFrame (async) |   |  
  | loop | @ | react-spring-rafz.esm.js?08aa:132
  | requestAnimationFrame (async) |   |  
  | loop | @ | react-spring-rafz.esm.js?08aa:132
  | requestAnimationFrame (async) |   |  
  | loop | @ | react-spring-rafz.esm.js?08aa:132
  | requestAnimationFrame (async) |   |  
  | loop | @ | react-spring-rafz.esm.js?08aa:132
  | requestAnimationFrame (async) |   |  
  | loop | @ | react-spring-rafz.esm.js?08aa:132
  | requestAnimationFrame (async) |   |  
  | loop | @ | react-spring-rafz.esm.js?08aa:132
  | requestAnimationFrame (async) |   |  
  | loop | @ | react-spring-rafz.esm.js?08aa:132
  | requestAnimationFrame (async) |   |  
  | loop | @ | react-spring-rafz.esm.js?08aa:132
  | requestAnimationFrame (async) |   |  
  | loop | @ | react-spring-rafz.esm.js?08aa:132
  | requestAnimationFrame (async) |   |  
  | loop | @ | react-spring-rafz.esm.js?08aa:132
  | requestAnimationFrame (async) |   |  
  | loop | @ | react-spring-rafz.esm.js?08aa:132
  | requestAnimationFrame (async) |   |  
  | loop | @ | react-spring-rafz.esm.js?08aa:132
  | requestAnimationFrame (async) |   |  
  | loop | @ | react-spring-rafz.esm.js?08aa:132
  | requestAnimationFrame (async) |   |  
  | loop | @ | react-spring-rafz.esm.js?08aa:132
  | requestAnimationFrame (async) |   |  
  | loop | @ | react-spring-rafz.esm.js?08aa:132
  | requestAnimationFrame (async) |   |  
  | loop | @ | react-spring-rafz.esm.js?08aa:132
  | requestAnimationFrame (async) |   |  
  | loop | @ | react-spring-rafz.esm.js?08aa:132
  | requestAnimationFrame (async) |   |  
  | loop | @ | react-spring-rafz.esm.js?08aa:132
  | requestAnimationFrame (async) |   |  
  | loop | @ | react-spring-rafz.esm.js?08aa:132
  | requestAnimationFrame (async) |   |  
  | loop | @ | react-spring-rafz.esm.js?08aa:132
  | requestAnimationFrame (async) |   |  
  | loop | @ | react-spring-rafz.esm.js?08aa:132
  | requestAnimationFrame (async) |   |  
  | loop | @ | react-spring-rafz.esm.js?08aa:132
  | requestAnimationFrame (async) |   |  
  | loop | @ | react-spring-rafz.esm.js?08aa:132
  | requestAnimationFrame (async) |   |  
  | loop | @ | react-spring-rafz.esm.js?08aa:132
  | requestAnimationFrame (async) |   |  
  | loop | @ | react-spring-rafz.esm.js?08aa:132
  | requestAnimationFrame (async) |   |  
  | loop | @ | react-spring-rafz.esm.js?08aa:132
  | requestAnimationFrame (async) |   |  
  | loop | @ | react-spring-rafz.esm.js?08aa:132
  | requestAnimationFrame (async) |   |  
  | loop | @ | react-spring-rafz.esm.js?08aa:132
```

### To Reproduce

I have the following use of `useTrail`:

```
    const [itemsStyles, itemsApi] = useTrail(length, () => ({
        from: { opacity: 0, y: -10 },
        to: { opacity: 1, y: 0 },
        config: {
          mass: 0.1,
          tension: 360,
          friction: 11,
      },
    }));
```

And then I call `itemsApi.start` in a memoized function (with useCallback):
```
const open = useCallback(() => {
    itemsApi.start({
        to: itemsVisible,
        config: openConfig,
    });
}, [itemsApi]);
```

This function is called inside `useEffect`, which on its hand is dependent on a component prop:
```
useEffect(() => {
  if (someProp) {
    open();
  }
}, [someProp, open]);
```

### Expected Behaviour

I expect it to behave as in 9.3.2 - without errors.

### Link to repo
[react-spring-bug-9.4.0](https://codesandbox.io/s/react-spring-bug-9-4-0-gs83c)
Try to change the version in CodeSandbox to 9.3.2 and see that the error will be gone.

**Comment by thexpand** [comment]
@joshuaellis I see that you were the one who released the last few versions, including the breaking minor version 9.4.0. Did you have a chance to take a look at the CodeSandbox, what could be the issue?

**Comment by neolectron** [comment]
I also have this problem and I provided a codesandbox to analyse this as well.
Thank you.

https://codesandbox.io/s/animated-email-button-csjqn

**Comment by thexpand** [comment]
I noticed that it works on `10.0.0-alpha.0`, but this version hasn't been updated since June 2021.
@neolectron By the way, your CodeSandbox uses that same alpha version and seems to be working fine with it, but when I forked your CodeSandbox and tried with `9.4.2` - it didn't work anymore - just like with my example.

**Comment by neolectron** [comment]
Yeah sorry, It was in 10.0.0-alpha-0 just to see where the bug comes from, but yeah it breaks in the latest update.

**Comment by thexpand** [comment]
Yes. By the way, for more clarity - I tested each available version of `react-spring` from CodeSandbox, including the alpha and beta ones. It works on `9.3.2`, `9.3.3` and even on `9.4.0-alpha.0`, but it breaks as soon as `9.4.0-beta.0`, so my best guess would be that it's something in between those 2 versions. However, I don't see a `9.4.0-alpha.0` tag in GitHub, so the best comparison that I could make is to compare `9.4.0-beta.0` with `9.3.2`: https://github.com/pmndrs/react-spring/compare/v9.3.2...v9.4.0-beta.0

However, I don't fully understand the internals of this library, so this speaks nothing to me.

PS FYI: npm has version `9.3.3`, but GitHub doesn't have such a tag. There's a clear inconsistency in the versions in npm and the available tags in GitHub.

**Comment by joshuaellis** [comment]
Hey all,

Sorry I only had time to get to this now, I appreciate this is a pretty high priority bug.

I've released `9.4.3-beta.0` which I believe fixes the issue, if anyone is able to test it and let me know, then I can release it as stable quicker.

Thanks again for the patience.

**Comment by thexpand** [comment]
@joshuaellis Hey there. Since there aren't many improvements that I can directly benefit from the new version, I can deal with having an older version of `react-spring` installed. Anyways, I tested with both @neolectron 's example and mine, but sadly the issue still seems to be there, even with `9.4.3-beta.0`.

**Comment by joshuaellis** [comment]
Shit, thanks for checking @thexpand, I just realised a bad merge into the beta branch myself, included my fix but didn't remove the bad code! I'll launch another beta now & check with those two sandboxes. 

I should have checked the merge better, my bad.

**Comment by joshuaellis** [comment]
Yep, that has correctly resolved the issue:

- https://codesandbox.io/s/animated-email-button-forked-g6ofl?file=/src/EmailInput.jsx
- https://codesandbox.io/s/react-spring-bug-9-4-0-forked-9sqh1?file=/src/App.js

Thanks again both for bringing this to my attention.

**Comment by thexpand** [comment]
@joshuaellis No worries :) Thanks. Now it works on both CodeSandbox examples.

I also decided to make a test in a real-world scenario, so I installed `9.4.3-beta.1` in the project that I've been experiencing issues with. I have 2 places where I was using `useTrail` - one without it being dependent on the local state, and another one - just exactly like the example in CodeSandbox. So far it seems to be working fine. I will leave the beta version installed on this project, as it is currently under development and it is not launched, yet. That will give me enough time to spot any issues, if such occur.

By the way, is there a release schedule or do you have something like a milestone-based release? I.e. what is the criteria to release stable versions and how can we help with that?
